baseURL = 'https://ezdify.alterxyz.org/'
title = 'Easy Dify Guide'
theme = "relearn"
metaDataFormat = "yaml"

[params]
author.name = "AlterXYZ"
images = ["others/Ereshkigal.JPG"]
# social.twitter = ""

themeVariant = [
    { identifier = "retro-auto", name = "Theme: Learn/Neon", auto = [
        "learn",
        "neon",
    ] },
    { identifier = "neon" },
    { identifier = "learn" },
    { identifier = "zen-auto", name = "Theme: Zen Auto", auto = [
        "zen-light",
        "zen-dark",
    ] },
    { identifier = "zen-light" },
    { identifier = "zen-dark" },

    { identifier = "relearn-auto", name = "Relearn Light/Dark", auto = [
    ] },
    { identifier = "relearn-light" },
    { identifier = "relearn-dark" },
    { identifier = "relearn-bright" },

    { identifier = "blue" },
    { identifier = "green" },
    { identifier = "red" },
]


editURL = "https://github.com/alterxyz/easy-dify-guide/edit/main/content/${FilePath}"
disableSearch = true
ordersectionsby = "weight"
collapsibleMenu = true
showVisitedLinks = true
disableShortcutsTitle = true
disableRootBreadcrumb = true

defaultContentLanguage = 'en'

[languages]
[languages.en]
languageName = 'Language: English'
title = 'Easy Dify'
weight = 1

[languages.zh]
languageName = '语言: 中文'
title = "简明 Dify"
languageCode = 'zh'
weight = 2
